In [1]:
import numpy as np

In [11]:
a=np.arange(12, 24)

In [12]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [17]:
a1=a.reshape(2, 6)
a2=a.reshape(4, 3)
a3=a.reshape(1, 12)
a4=a.reshape(6, 2)
a5=a.reshape(3, 4)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15 16 17 18 19 20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [20]:
a11=a.reshape(6, -1)
a12=a.reshape(4, -1)
a13=a.reshape(-1, 12)
a14=a.reshape(-1, 6)
a15=a.reshape(12, -1)
print(a11)
print(a12)
print(a13)
print(a14)
print(a15)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15 16 17 18 19 20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [21]:
x=np.arange(12, 24)

In [22]:
dos=x.reshape(2,6)

In [23]:
y=dos.reshape(12,1)

In [24]:
print(x)
print(y)

[12 13 14 15 16 17 18 19 20 21 22 23]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [25]:
ran_mas=np.random.randn(3,4)
print(ran_mas)

[[ 1.30820267  1.15985245 -1.85515487  0.97474359]
 [ 0.34209982 -0.02624876  0.80497113 -0.03241519]
 [ 1.60006503 -1.14644868  1.93463203  0.15632722]]


In [26]:
print(ran_mas.size)

12


In [27]:
new_mas=ran_mas.flatten()

In [28]:
print(new_mas.size)

12


In [31]:
print(new_mas)

[ 1.30820267  1.15985245 -1.85515487  0.97474359  0.34209982 -0.02624876
  0.80497113 -0.03241519  1.60006503 -1.14644868  1.93463203  0.15632722]


In [30]:
a=np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [34]:
b=np.arange(20, 1, -2)
b=b.reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [47]:
a=np.arange(0, 12)
A=a.reshape(4,3)
print(a)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [48]:
At=A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [49]:
B=np.dot(A,At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [50]:
B.shape

(4, 4)

In [51]:
B_inv=np.linalg.inv(B)
B_inv

LinAlgError: Singular matrix

In [43]:
np.random.seed(42)

In [44]:
c=np.random.randint(0, 16,16)

In [45]:
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [46]:
C=c.reshape(4,4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [52]:
D = B + C * 10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [53]:
det=np.linalg.det(D)
det

-28511999.999999944

In [54]:
rank=np.linalg.matrix_rank(D)

In [55]:
rank

4

In [56]:
D_inv=np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [57]:
D_inv=np.where(D_inv<0, 0,1)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [58]:
E=np.where(D_inv==1, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])

In [59]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [60]:
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])