In [9]:
import numpy as np
import pandas as pd

In [1]:
from sklearn.datasets import load_boston
boston = load_boston()
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [2]:
data = boston["data"]

In [3]:
feature_names = boston["feature_names"]

In [4]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [5]:
feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [6]:
data.shape

(506, 13)

In [7]:
target = boston["target"]

In [10]:
X = pd.DataFrame(data, columns=feature_names)

In [11]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: float64(13)
memory usage: 51.5 KB


In [13]:
y = pd.DataFrame(target, columns=["price"])

In [14]:
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   price   506 non-null    float64
dtypes: float64(1)
memory usage: 4.1 KB


In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [17]:
X_train.shape

(354, 13)

In [18]:
X_test.shape

(152, 13)

In [19]:
y_train.shape

(354, 1)

In [20]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [21]:
lr.fit(X_train, y_train)

LinearRegression()

In [22]:
y_pred = lr.predict(X_test)
y_pred.shape

(152, 1)

In [23]:
check_test = pd.DataFrame({
 "y_test": y_test["price"],
 "y_pred": y_pred.flatten(),
})

In [24]:
check_test.shape

(152, 2)

In [25]:
check_test.head

<bound method NDFrame.head of      y_test     y_pred
493    21.8  20.701109
428    11.0  14.749202
146    15.6  15.910227
341    32.7  30.319759
282    46.0  40.505932
..      ...        ...
477    12.0  11.688837
80     28.0  28.342659
54     18.9  15.327080
505    11.9  21.939075
118    20.4  20.730746

[152 rows x 2 columns]>

In [26]:
from sklearn.metrics import r2_score

In [39]:
res_1=r2_score(check_test["y_pred"], check_test["y_test"])
res_1

0.6294420424615166

In [40]:
from sklearn.ensemble import RandomForestRegressor

In [41]:
model = RandomForestRegressor(n_estimators=1000, max_depth=12, random_state=42)

In [42]:
model.fit(X_train, y_train.values[:, 0])

RandomForestRegressor(max_depth=12, n_estimators=1000, random_state=42)

In [45]:
check_test = pd.DataFrame({
 "y_test": y_test["price"],
 "y_pred": y_pred.flatten(),
})

In [46]:
y_pred = model.predict(X_test)

In [47]:
res_2=r2_score(check_test["y_pred"], check_test["y_test"])
res_2

0.814438569336096

In [48]:
#т.к.res_2>res_1, то модель 2 работает лучше

In [49]:
?RandomForestRegressor

In [50]:
#feature_importances_ : ndarray of shape (n_features,) 
#    The impurity-based feature importances.
#    The higher, the more important the feature.
#    The importance of a feature is computed as the (normalized)
#    total reduction of the criterion brought by that feature.  It is also
#    known as the Gini importance.

In [51]:
print(model.feature_importances_)

[0.02875278 0.00126427 0.00777897 0.00116399 0.01503785 0.52775742
 0.00975039 0.07517702 0.00429181 0.01031694 0.02208737 0.01223089
 0.28439029]


In [52]:
model.feature_importances_.sum()

1.0

In [53]:
max_pr=model.feature_importances_.argmax()

In [54]:
max_pr

5

In [57]:
a = model.feature_importances_

In [58]:
a

array([0.02875278, 0.00126427, 0.00777897, 0.00116399, 0.01503785,
       0.52775742, 0.00975039, 0.07517702, 0.00429181, 0.01031694,
       0.02208737, 0.01223089, 0.28439029])

In [63]:
b=np.delete(a, 5)

In [64]:
b

array([0.02875278, 0.00126427, 0.00777897, 0.00116399, 0.01503785,
       0.00975039, 0.07517702, 0.00429181, 0.01031694, 0.02208737,
       0.01223089, 0.28439029])

In [71]:
if np.argmax(b)>=max_pr:
    max_pr2=np.argmax(b)+1
else:
    max_pr2=np.argmax(b)
max_pr2

12